### PR TITLE
Fix rotate and add instructions

### PR DESCRIPTION
**Pull request by samrussell**
- Fixed bug passing registers whole when they should be passed as indices (I think?)
- Fixed bug where rotate instructions were using the wrong var names
- Added missing IX and IY sub registers

### CODE REVIEW

**Comment by samrussell** [comment]
Tested on Alex Kidd SMS ROM

**Comment by lwerdna** [comment]
Thanks for the PR!

**Comment by lwerdna** [comment]
@samrussell Would you mind attaching or linking the Alex Kidd SMS ROM for use in test cases going forward?

**Comment by samrussell** [comment]
Technically it's still under copyright despite being older than me so I'm reluctant to share it, but it can be found on various sega master system rom websites

**Pull request merged**
